## NumPy Function

In [ ]:
import numpy as np

### Aggregate function

In [ ]:
arr=np.array([10,20,30,40])
print("Sum: ",np.sum(arr))
print("Max: ",np.max(arr))
print("Min: ",np.min(arr))
print("count: ",arr.size)
print("Comulitive Sum: ",np.cumsum(arr))
print("Comulitive product: ",np.cumprod(arr))


### Statistical function


In [ ]:
import statistics as st
sales=np.array([200,180,150,250,300,20,230,500,500])
print("Mean: ",np.mean(sales))
print("Median: ",np.median(sales))
print("Mode: ",st.mode(sales))
print("Standard Division: ",np.std(sales))

In [21]:
price=np.array([120,180,200,210,220,300])
sales=np.array([5,9,10,12,19,52])
print(np.corrcoef([price,sales]))

[[1.         0.90193381]
 [0.90193381 1.        ]]


In [27]:
#data structure: [resturant_id,2021,2022,2023]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

#1.shape of the data
print("shape: ",np.shape(sales_data))
#2. print sample data for first three resturant
print("Sample:\n ",sales_data[:3,:5])
#3.total sale per year

#4.maximum sale per resturant
for i in range(1,6):
    print("Maximum sale of resturant: ",i,np.max(sales_data[i,:5]))
#5.maximum sale per year
#6.average sales of every resturant
#7.average comulitive sale occur on all resturant
#8.Monthly average for all resturant every year

shape:  (5, 5)
Sample:
  [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]
Maximum sale of resturant:  1 190000
Maximum sale of resturant:  2 300000
Maximum sale of resturant:  3 270000
Maximum sale of resturant:  4 230000


IndexError: index 5 is out of bounds for axis 0 with size 5